import pandas as pd
import numpy as np

#***********working with text datas**************
s = pd.Series(['Tom','Jerry','@Nobita','Suzuka',np.nan,'1234','Doreamon'])
print(s)
print(s.str.lower())
print(s.str.upper())
print(s.str.len())
print("after stripping")
print(s.str.strip())
print("Split pattern")
print(s.str.split(' '))
print(s.str.cat(sep='_'))
print(s.str.get_dummies())
print(s.str.contains(' '))
print("after replacing @ with $")
print(s.str.replace('@','$'))
print(s.str.repeat(2))
print("the number of m in each string")
print(s.str.count('m'))
print("string that starts with T")
print(s.str.startswith('T'))
print("strings ends with T")
print(s.str.endswith('t'))
print(s.str.find('u'))
print(s.str.findall('e'))
print(s.str.swapcase())
print(s.str.islower())
print(s.str.isupper())
print(s.str.isnumeric())

#*****************options and customization************
print(pd.get_option("display.max_rows"))
print(pd.get_option("display.max_columns"))
pd.set_option("display.max_rows",80)
print(pd.get_option("display.max_rows"))
pd.set_option("display.max_columns",30)
print(pd.get_option("display.max_columns"))
pd.reset_option("display.max_rows")
print(pd.get_option("display.max_rows"))
pd.describe_option("display.max_rows")
with pd.option_context("display.max_rows",10):
    print(pd.get_option("display.max_rows"))
